### PR TITLE
Autoconf macro for finding lua shared libraries. Fix #23

### LINKED ISSUE #23: Lua broken on debian machines
Lua is broken on debian (and possibly other) machines.

See https://issues.apache.org/jira/browse/THRIFT-2914.

The current makefile is set to ``-llua``, however, debian will require ``-llua5.2`` for the shared library.

### PR DESCRIPTION
**Pull request by tony**
Add autoconf macro for cross-platform lua detection.

See also:

- https://issues.apache.org/jira/browse/THRIFT-2914
- https://github.com/apache/thrift/commit/468e63b36d7ae4c1071d358eefcb253d83704c27

### CODE REVIEW

**Comment by jeaye** [comment]
Ouch, I'm really hesitant to bring in autoconf for this solution. I was thinking, in the configure script, we'd just check for `[ -f /etc/debian_version ] && ld_platform_libs=-llua5.2` and otherwise do the normal `-llua`. In fact, I was just implementing this. Opinion?

**Comment by jeaye** [comment]
We'll likely need to check `/etc/lsb-release` for Ubuntu and the like as well. Unfortunately, build systems are always a lose-lose scenario.

**Comment by jeaye** [comment]
@tony I've pushed up a change to the `debian` branch. Would you mind giving it a go? Just pull, configure, and try making.

**Comment by jeaye** [comment]
This has been fixed. Thanks again.

**Comment by tony** [comment]
@jeaye : 
> Ouch, I'm really hesitant to bring in autoconf for this solution.

To avoid overhead? License? What's the issue? I'm new to autotools and co., but I am to understand that a macro would be the more portable option. We rely on tools like that because handling edge  cases in ``./configure`` can't assure us compatibility. There have been vague reports of compilation issues, so I'd prefer to err on the side of caution.

What would the the alternative to autoconf that would assure portability build system layouts / library locations out there?

**Comment by tony** [comment]
> @tony I've pushed up a change to the debian branch. Would you mind giving it a go? Just pull, configure, and try making.

Debian works. The newest master branch (which I think has the debian branches changes at this point) works.

I am interested in your take / info on my comment above. I am new to the autotools scene.

**Comment by jeaye** [comment]
> To avoid overhead? License? What's the issue? I'm new to autotools and co., but I am to understand that a macro would be the more portable option. We rely on tools like that because handling edge cases in ./configure can't assure us compatibility. There have been vague reports of compilation issues, so I'd prefer to err on the side of caution.

1. Though it looks and feels similar, I'm not currently using autotools; this addition doesn't really fit.
2. Sure, it's portable; it's also almost 700 lines of  code added to the repo just to handle this issue. If I'm going to choose a more portable approach, it's not going to involve poluting the repo with code like this.
3. I agree that the current approach is flawed; still, autotools has a terrible reputation for a reason. If I'm going to choose something else, I'll opt for cmake or scons or gradle, etc.

I haven't yet invested enough time to decide which of these is the most sane, so I've been using the (admittedly limited and naive) simple configure script and Makefile approach. I'm absolutely interested in moving to one of these (for all of my projects), but autotools is somewhere at the bottom of the list.

> Debian works. The newest master branch (which I think has the debian branches changes at this point) works.

Thanks for letting me know and especially for reporting. I've created an Ubuntu system for testing now, which should catch any regressions.

**Comment by tony** [comment]
@jeaye Why are we here? To highlight with clang.

Why do people use clang? To write portable code C and C++. When releasing a source-based distribution of something, the burden to make the code buildable across platforms rests on the project. I think for that reason, it deserves are high priority.

I'm working a branch to get freebsd working and seeing if the shell script can be made POSIX compliant to remove the bash dependency (https://github.com/tony/color_coded/tree/freebsd).

I'm interested in seeing what approaches beyond a shell script you'd consider for building portable across systems (simply as a matter of learning on my end). I'm sure you're aware of YouCompleteMe and it's configurable system for grabbing clang / using the system's clang.

You're the expert on this, I'm interested in this for educational purposes, as I happen to be dipping my toes into C and build tools. And of course, as you likely know, FreeBSD uses clang and ``/usr/src`` is a treasure trove of great C code.

**Comment by jeaye** [comment]
> I think for that reason, it deserves a high priority.

I'm very concerned about this. Not having invested enough time to make a decision yet doesn't mean I haven't invested much time. Unfortunately, when it comes to build systems with the capabilities of finding packages across distributions and OSs, we're down to CMake and Autotools.

> I'm sure you're aware of YouCompleteMe and it's configurable system for grabbing clang / using the system's clang.

YCM uses CMake under the hood, but its main interface is actually a non-standard "install" script which calls into a `build.py` file and doesn't accept _any_ standard flags, nor does it even support `--help`. It's not something I want to emulate.

> I'm interested in seeing what approaches beyond a shell script you'd consider for building portable across systems (simply as a matter of learning on my end).

At this point, I think the best approach is to switch to CMake. If you're itching to get things working, you're welcome to give this a shot. If you do, please let me know so I don't duplicate the work. Otherwise, I'll aim to get it working (in either CMake or something else that comes up) this week.

> And of course, as you likely know, FreeBSD uses clang and /usr/src is a treasure trove of great C code.

I'm not experienced with FreeBSD, but I'm excited to see color_coded is getting ported. Aside from the build system hoopla, if there're any other issues you run into during your porting, feel free to ping me.

**Comment by tony** [comment]
Considering my lack of experience currently with build tools, I'm bordering on being from the peanut gallery. 

If you can lead me down the right path - what part of cmake handles' the type of thing the autoconf lua macro was doing?

``build.py`` - yes I saw that in YouCompleteMe and felt that you wouldn't like that as a build tool (hehe) however I did feel you could gain some portability insight out of it. YCM does download clang dependency and allow building from the OS's clang.  When you say ``--help``, unless you mean something else, i'm pretty sure it gives a help response. Environment variables do come into effect  when invoking ``build.py`` (such as ``export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/llvm35/lib/``). That said, a custom, pure python build tool isn't doing a favor. The obscurity of not using a more popular build system isn't up to par for a tool that's meant to help developer's who know how to use build tools already anyway.

For the cmake route, neovim has lua / downloadable third party libs and is pretty much on the cutting edge: https://github.com/neovim/neovim/tree/master/cmake + https://github.com/neovim/neovim/tree/master/third-party/cmake + https://github.com/neovim/neovim/blob/master/CMakeLists.txt.

If we pull something like this off, maybe we could turn the tables and get ycm to switch to cmake.

**Comment by jeaye** [comment]
I started earlier today on an initial CMake hack. I currently have it building successfully on OS X, but it doesn't do the fancy work of downloading clang, extracting, configuring the proper directories, generating header files, etc. The directories are currently hardcoded, but it does use the portable approaches for finding curses (needed by clang), zlib, and lua.

Once I have this in a stable state (tonight or tomorrow) and it reaches parity, we'll need to do some good testing across platforms, including FreeBSD (I could use your help for this), and maybe even Windows.

**Comment by jeaye** [comment]
It's not polished, but it's now working for me on OS X and Arch Linux. If you want to try it out, checkout the `cmake` branch. It's late night for me now, but I'll get back at it tomorrow and polish things up. Hopefully tomorrow we can get it into `master`.

**Pull request closed without merging**
