### PR TITLE
Simplify finding lua

### PR DESCRIPTION
**Pull request by UnrealQuester**
There are cmake find modules for lua 5.0 and 5.1. The current cmake
master however does not contain a FindLua52. Unless a distribution adds
this script in their repos, searching for lua 5.2 will always fail and
we will fall back to lua 5.1 if it is available. If it is not, the
generic FindLua.cmake will find lua 5.2. This is a problem on systems
where both 5.1 and 5.2 are installed, as 5.2 will never be selected. As
the FindLua.cmake searches for versions >= 5.0 and returns the highest
version it finds we can just use that.

The FindLua package only got added with CMake 3.0.0 so we have to add
our own.

### CODE REVIEW

**Comment by jeaye** [comment]
I don't think this simplified anything; it's more than 10x more code to do the same thing. The order in which I search is intentional:

- color_coded has been tested the most with Lua 5.2
- Lua 5.1 has been a fallback, but hasn't shown issues
- If we can't find either, just try to find anything; I explicitly want to try the above versions first

**Comment by UnrealQuester** [comment]
The FindLua.cmake is only included to remain compatible to cmake < 3.0.0 and is copied from their official repo. The problem is that FindLua52 does not exist, at least not in their repo and not even in debian testing. Unless a maintainer adds it for their distribution, we can't count on it beeing available. The only reason it works with 5.2 is because 5.1 fails and the generic FindLua finds 5.2. For someone who has cmake < 3.0.0 this means either only 5.1 or nothing.

The current state works like this:

Installed Lua Versions  | CMake version | Selected Lua Version
----------------------------- | ----------------- | ---------------------------
5.1 | * | 5.1
5.2 | >=3.0.0 | 5.2
5.2 | < 3.0.0 | None
5.2 and 5.1 | * | 5.1

This PR changes that to instead work like this:

Installed Lua Versions  | CMake version | Selected Lua Version
----------------------------- | ----------------- | ---------------------------
5.1 | * | 5.1
5.2 | * | 5.2
5.2 and 5.1 | * | 5.2

If we only have to support cmake 3.0.0 and higher, we can just leave the script out.

**Comment by jeaye** [comment]
How can we do this without copying in the whole FindLua from cmake? The more lines of code in the repo, the more there is to maintain. Is there a more minimal solution which gives us better coverage?

**Comment by UnrealQuester** [comment]
@jeaye repushed and got it down to about 53 lines of code. Most of which is a list of possible install directories. The list of minor versions may be tweaked to allow for more versions like 5.0 and 5.3.

**Comment by jeaye** [comment]
Wouldn't searching in the following order have the same effect?

1. FindLua
2. FindLua52
3. FindLua51

**Comment by UnrealQuester** [comment]
Does your cmake install contain FindLua52? It does not seem to exist in mine and I can't find it in the cmake repo. I know that Debian stable and Gentoo do not have it (and I am assuming neither does Ubuntu). FindLua is only available for cmake 3.0.0 and above. If you are okay with not supporting earlier versions, just FindLua will be enough.

**Comment by jeaye** [comment]
On Tue, May 12, 2015 at 04:33:28AM -0700, UnrealQuester wrote:
>    Does your cmake install contain FindLua52? It does not seem to exist in
>    mine and I can't find it in the cmake repo. I know that Debian stable and
>    Gentoo do not have it (and I am assuming neither does Ubuntu). FindLua is
>    only available for cmake 3.0.0 and above. If you are okay with not
>    supporting earlier versions, just FindLua will be enough.

It exists on Arch Linux, at least, which is what I was using when I wrote color_coded.

**Comment by UnrealQuester** [comment]
> It exists on Arch Linux, at least, which is what I was using when I wrote color_coded.

Ah, okay. The order in which the checks are performed depend on which systems you want to support. If you don't want to support systems with cmake < 3.0.0 then the version you posted earlier will work just fine. I don't think we even need FindLua52 and FindLua51 in that case as FindLua searches for these versions as well. If you want to support cmake < 3.0.0, we will need to include our own FindLua.

**Comment by jeaye** [comment]
Well, you win. #56 was enough for me to reconsider the switch. Are there any more changes you want to get in before I merge?

**Comment by UnrealQuester** [comment]
I would really love to live without FindLua.cmake, but this would require cmake > 3.0.0. Many systems still ship with an older version. There are no more changes I would like to make.

**Comment by jeaye** [comment]
Alrighty. Thanks for the work!

**Comment by jeaye** [comment]
This doesn't build on OS X, it seems. Looking into it.

```text
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found 64bit system
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX1Y
-- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
-- Looking for Lua >= 5.1
CMake Error at cmake/lua.cmake:6 (if):
  if given arguments:

    "VERSION_LESS" "5.1"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/jeaye/.vim/bundle/color_coded/build/CMakeFiles/CMakeOutput.log".
```

**Comment by jeaye** [comment]
Looks like `LUA_VERSION_STRING` isn't set at all, in the new FindLua file.

**Comment by jeaye** [comment]
I have removed the check for the version such that this can build on systems that treat CMake warnings as errors. If you'd like to get it back in, since we don't check that it's >= 5.1 now, let me know.

**Pull request merged**
