### PR TITLE
Instructions for building from FreeBSD / PCBSD

### PR DESCRIPTION
**Pull request by tony**

### CODE REVIEW

**Comment by tony** [comment]
This isn't working, I'm going to keep working on it.

**Comment by tony** [comment]
https://github.com/jeaye/color_coded/blob/master/cmake/clang/download.cmake#L53 looking at this

**Comment by tony** [comment]
@jeaye Much better, added search paths for FreeBSD's library locations.

**Comment by jeaye** [comment]
This is perfect. Thanks, @tony.

**Pull request merged**
